env:
  APP_VERSION: 0760c30be85e94ff1651b9b159d4eb4aa499583e
  IMAGE_NAME: borpatika/ocr-app

django:
  secretKey: "password"
  debug: "False"
  allowedHosts: "*"

postgres:
  db: ocrdb
  user: ocruser
  password: ocrpassword

minio:
  accessKey: minioadmin
  secretKey: minioadmin
  bucket: ocr-images

rabbit:
  APP_VERSION: 0760c30be85e94ff1651b9b159d4eb4aa499583e
  IMAGE_NAME: borpatika/ocr-app-mq-worker