env:
  APP_VERSION: 49f58cb616ba27842ca28126aa20195efad5efdc
  IMAGE_NAME: borpatika/ocr-app

django:
  secretKey: "password"
  debug: "False"
  allowedHosts: "*"

postgres:
  db: ocrdb
  user: ocruser
  password: ocrpassword

minio:
  accessKey: minioadmin
  secretKey: minioadmin
  bucket: ocr-images
