env:
  APP_VERSION: f134497dc15313177c24c0774514630c8f752fae
  IMAGE_NAME: borpatika/ocr-app

django:
  secretKey: "password"
  debug: "False"
  allowedHosts: "*"

postgres:
  db: ocrdb
  user: ocruser
  password: ocrpassword

minio:
  accessKey: minioadmin
  secretKey: minioadmin
  bucket: ocr-images
